### ISSUE TITLE
睡眠唤醒后重启 代码如下 求大神支持

### ISSUE THREAD

**Issue by ccnoxx** [csrutil/DeskMini#11]
panic(cpu 4 caller 0xffffff80009fe647): "AppleHDAHDMI_DPDriver::setPowerState(0xffffff9386625100 : 0xffffff7f9e49d348, 0 -> 1) timed out after 10147 ms"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.50.7/iokit/Kernel/IOServicePM.cpp:5382
Backtrace (CPU 4), Frame : Return Address
0xffffffc103213ac0 : 0xffffff80002bc66d mach_kernel : _handle_debugger_trap + 0x3dd
0xffffffc103213b10 : 0xffffff80003ff073 mach_kernel : _kdp_i386_trap + 0x143
0xffffffc103213b50 : 0xffffff80003ef6aa mach_kernel : _kernel_trap + 0x55a
0xffffffc103213ba0 : 0xffffff8000261a2f mach_kernel : _return_from_trap + 0xff
0xffffffc103213bc0 : 0xffffff80002bbf0d mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffc103213ce0 : 0xffffff80002bc1f8 mach_kernel : _panic_trap_to_debugger + 0x268
0xffffffc103213d50 : 0xffffff8000abee1a mach_kernel : _panic + 0x54
0xffffffc103213dc0 : 0xffffff80009fe647 mach_kernel : __ZN9IOService12ackTimerTickEv + 0x6b7
0xffffffc103213e10 : 0xffffff80009fdf69 mach_kernel : __ZN9IOService21actionAckTimerExpiredEP8OSObjectPvS2_S2_S2_ + 0x9
0xffffffc103213e20 : 0xffffff8000a16a1e mach_kernel : __ZN10IOWorkLoop9runActionEPFiP8OSObjectPvS2_S2_S2_ES1_S2_S2_S2_S2_ + 0x3e
0xffffffc103213e60 : 0xffffff80009fcce8 mach_kernel : __ZN9IOService17ack_timer_expiredEPvS0_ + 0x38
0xffffffc103213e80 : 0xffffff8000301345 mach_kernel : _thread_call_delayed_timer + 0x4a5
0xffffffc103213ef0 : 0xffffff8000302254 mach_kernel : _thread_call_delayed_timer + 0x13b4
0xffffffc103213fa0 : 0xffffff800026113e mach_kernel : _call_continuation + 0x2e

Process name corresponding to current thread: kernel_task
Boot args: igfxonln=1 dart=0 keepsyms=1 darkwake=0 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20B50

Kernel version:
Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
Kernel UUID: 84C6DC45-6B02-335F-9439-5D2A9BC385A4
KernelCache slide: 0x0000000000000000
KernelCache base:  0xffffff8000200000
Kernel slide:      0x0000000000010000
Kernel text base:  0xffffff8000210000
__HIB  text base: 0xffffff8000100000
System model name: iMac20,1 (Mac-CFF7D910A743CAAF)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 64709988378
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000000f110412c4
  Sleep   : 0x0000000c4c60ba51 0x00000007dca16f0a 0x0000000000000000
  Wake    : 0x0000000ca0990e66 0x0000000075c32435 0x0000000c62069e39
last started kext at 8383439674: >AudioAUUC	1.70 (addr 0xffffff7f9f9d5000, size 12288)
loaded kexts:
as.acidanthera.mieze.!IMausi	1.0.4
ru.joedm.SMCSuperIO	1.1.8
as.vit9696.SMCProcessor	1.1.8
as.vit9696.VirtualSMC	1.1.8
org.acidanthera.NVMeFix	1.0.4
as.vit9696.WhateverGreen	1.4.4
as.vit9696.!AALC	1.5.4
as.vit9696.Lilu	1.4.9
>AudioAUUC	1.70
>AGPM	119
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
@filesystems.autofs	3.0
@fileutil	20.036.15
>!AGraphicsDevicePolicy	6.1.27
@AGDCPluginDisplayMetrics	6.1.27
>!AUpstreamUserClient	3.6.8
>!AMCCSControl	1.14
>pmtelemetry	1
>LuaHardwareAccess	1.0.16
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
|IO!BSerialManager	8.0.1f5
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
>!ADiskImages2	1
>!AHDAHardwareConfigDriver	283.15
>!A!IKBLGraphics	16.0.0
>ACPI_SMC_PlatformPlugin	1.0.0
>!AHDA	283.15
>!A!ICFLGraphicsFramebuffer	16.0.0
>!AFIVRDriver	4.1.0
>!A!IPCHPMC	2.0.1
>!A!ISlowAdaptiveClocking	4.0.0
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.41.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@private.KextAudit	1.0
@filesystems.apfs	1677.50.1
>AirPort.BrcmNIC	1400.1.1
>!AAHCIPort	346
>!ARTC	2.0
>!AACPIButtons	6.1
>!AHPET	1.8
>!ASMBIOS	2.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	310
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@kext.triggers	1.0
>!AGraphicsControl	6.1.27
>!ASMBus!C	1.0.18d1
|IOSMBus!F	1.1
|IOSerial!F	11
|IOAVB!F	900.12
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
|IONDRVSupport	585
@!AGPUWrangler	6.1.27
|IOAccelerator!F2	439.35.4
@!AGraphicsDeviceControl	6.1.27
>!ASMBusPCI	1.0.14d1
>!AHDA!C	283.15
|IOHDA!F	283.15
|IOGraphics!F	585
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
>IOPlatformPlugin!F	6.0.0d8
|IOSlowAdaptiveClocking!F	1.0.0
@plugin.IOgPTPPlugin	900.11
|IOEthernetAVB!C	1.1.0
>usb.cdc.ecm	5.0.0
>usb.cdc.ncm	5.0.0
>usb.IOUSBHostHIDDevice	1.2
>!UMergeNub	900.4.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!ABSDKextStarter	3
|IOSurface	289.3
@filesystems.hfs.encodings.kext	1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AXsanScheme	3
|IO80211!F	1200.12.2b1
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
|IOAHCI!F	294
|IONVMe!F	2.1.0
>!AEFINVRAM	2.1
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOTimeSync!F	900.11
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.1f5
|IOReport!F	47
|IO!BPacketLogger	8.0.1f5
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.40.9
|IOUSBMass!SDriver	184.40.6
|IOSCSIBlockCommandsDevice	436.40.6
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.40.6
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1

**Comment by ccnoxx** [comment]
配置如下：
CPU：INTEL I5 8400
Wi-Fi: BCM94360CS2
SSD: 512GB WD SN720 NVMe
RAM: 16GB x 2 DDR4 2400

**Comment by csrutil** [comment]
`System model name: iMac20,1 (Mac-CFF7D910A743CAAF)` 你修改了model?

**Comment by ccnoxx** [comment]
> `System model name: iMac20,1 (Mac-CFF7D910A743CAAF)` 你修改了模型吗？

是的，我改过了模型，在生成三码的时候。
听您的意思应该是模型问题了，那我修改回去重新生成三码试试。
非常感谢您的回复，谢谢

**Comment by ccnoxx** [comment]
> `System model name: iMac20,1 (Mac-CFF7D910A743CAAF)` 你修改了model?

我尝试恢复model为：System model name: iMac19,1 (Mac-AA95B1DDAB278B95)
尽管如此，睡眠唤醒后依然会重启。我们的配置何其的相似，我怎么也想不通为何会发生这样的事，我的天呐。

**Comment by csrutil** [comment]
@ccnoxx Please clean install the macOS, and don't modify the model on the plist. you can replace the serial on site https://www.appleserial.com/

**Comment by ccnoxx** [comment]
> @ccnoxx Please clean install the macOS, and don't modify the model on the plist. you can replace the serial on site https://www.appleserial.com/

我有时间重装试一下吧，作为一个程序员，这是我的生产力工具，重新安装macOS后在恢复状态还是比较费劲的。十分感谢您， 抱拳。

**Comment by hekaimsbl** [comment]
1.重新定制你的USB端口补丁
2.重新定制缓冲帧补丁

**Comment by ccnoxx** [comment]
> 1.重新定制你的USB端口补丁
> 2.重新定制缓冲帧补丁

1、我检查了USB补丁，每一个都是准确的。
2、尝试重新定制缓冲帧补丁：
我在学习和尝试的过程中发现0x3E9B这个型号默认会把所有接口认为是DP，但是在接口中调整类型为DP+HDMI并没有效果，
我看到另外有一个兄弟和我一样用DP+HDMI会出现睡眠重启或HDMI花屏等问题，不知道是不是我的修改方式有问题。

**Comment by hekaimsbl** [comment]
> > 1.重新定制你的USB端口补丁
> > 2.重新定制缓冲帧补丁
> 
> 1、我检查了USB补丁，每一个都是准确的。
> 2、尝试重新定制缓冲帧补丁：
> 我在学习和尝试的过程中发现0x3E9B这个型号默认会把所有接口认为是DP，但是在接口中调整类型为DP+HDMI并没有效果，
> 我看到另外有一个兄弟和我一样用DP+HDMI会出现睡眠重启或HDMI花屏等问题，不知道是不是我的修改方式有问题。

我确定这两个问题会导致睡眠重启、重启花屏问题
关于Usb端口补丁可以找同类机型的仓库试试
缓冲帧补丁尽量先用简单的尝试

**Comment by csrutil** [comment]
长时间没有讨论，关闭啦（如有需要、可重新打开
