### ISSUE TITLE
The dual monitor is not working properly.

### ISSUE THREAD

**Issue by mz-soft** [csrutil/DeskMini#13]
display:DELL U2417H *2

I tried 10.15.4 to upgrade 11.1 yesterday but failed.

Using Recovery to connect the DP display alone, the online installation of 11.1 was successful.

Then boot up and access the DP HDMI dual screen HDMI flower screen. You need to restart the HDMI display or plug in HDMI.

**Comment by csrutil** [comment]
Please check your BIOS settings
