### ISSUE TITLE
蓝牙无法正常启用

### ISSUE THREAD

**Issue by Havord** [csrutil/DeskMini#15]
同款网卡，用了之后Wi-Fi正常蓝牙无法启用

**Comment by csrutil** [comment]
请检查你的网卡在Windows上是否正常使用，且提供日志。

**Comment by Havord** [comment]
windows上正常，日志如何提供？

**Comment by easyworld** [comment]
同款网卡，用了之后Wi-Fi正常蓝牙无法启用，系统报告中蓝牙为空，USB也无蓝牙设备

**Comment by easyworld** [comment]
观察发现USBPorts.kext[此处](https://github.com/appleserial/DeskMini/blob/master/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist#L25)和[此处](https://github.com/appleserial/DeskMini/blob/master/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist#L116)中写了iMac19,1-XHC关键字，猜测与机型有关，调整Config.plist中PlatformInfo设备型号为iMac19,1，故障消失，蓝牙可用了

**Comment by csrutil** [comment]
@easyworld @Havord 为什么你们修改kext的内容？

**Comment by easyworld** [comment]
> @easyworld @Havord 为什么你们修改kext的内容？

我没有修改kext。我修改了Config.plist中PlatformInfo设备型号。
