### ISSUE TITLE
Extended USB 2.0 doesn't work

### ISSUE THREAD

**Issue by larryhuang** [csrutil/DeskMini#16]
I bought Deskmini extended USB 2.0 cable.
It doesn't work.

**Comment by csrutil** [comment]
Yes, you need to customize your USBPorts.kext, thanks!

**Comment by larryhuang** [comment]
Could you give some clue about how to customize the USB Port?
Thank you

**Comment by vivikuyo** [comment]
大佬..同样的问题..求解，非常感谢！

**Comment by vivikuyo** [comment]
> Could you give some clue about how to customize the USB Port?
> Thank you

提取这个哥们的USBPort.kext替换进去。https://github.com/leogitpro/Hackintosh-DeskMini310-OC

**Comment by larryhuang** [comment]
It worked
Thank you

**Comment by larryhuang** [comment]
提取这个哥们的USBPort.kext替换进去。
https://github.com/leogitpro/Hackintosh-DeskMini310-OC

vivikuyo ***@***.***> 於 2021年4月10日 週六 下午4:50寫道：
