### ISSUE TITLE
欢迎加入deskmini-h310的机油群

### ISSUE THREAD

**Issue by SnailDove** [csrutil/DeskMini#2]
![](http://q9kvrafcq.bkt.clouddn.com/snaildove.github.io/deskmini310/deskmini310-hackers%E7%BE%A4%E4%BA%8C%E7%BB%B4%E7%A0%81.png)
里面主要是热心的程序员，非诚勿扰，禁止皮条客广告商加入！
你的telegram太高端了

**Comment by csrutil** [comment]
谢谢好意，个人不用QQ。
