### ISSUE TITLE
无线网卡过长

### ISSUE THREAD

**Issue by FrazeWu** [csrutil/DeskMini#4]
按README里面买的网卡发现直接盖住后边的芯片了，SSD也装不上螺丝了，凑活能用。不知道是不是买错了。

**Comment by csrutil** [comment]
你买的型号是什么样子的?

**Comment by FrazeWu** [comment]
94360cs2加转接板，长还好说，我的ssd后面还有颗粒，现在上不上螺丝，我拿胶带沾上了，将就用。
