### ISSUE TITLE
用这个EFI全新安装bigsur 11.0.1成功，目前一切正常。

### ISSUE THREAD

**Issue by 378210331** [csrutil/DeskMini#6]

**Comment by zj9495** [comment]
升级到11.0.1以后睡眠重启，之前10.15.7版本没遇到过这个问题。大家遇到过吗？

**Comment by zlylong** [comment]
> 升级到11.0.1以后睡眠重启，之前10.15.7版本没遇到过这个问题。大家遇到过吗？

没有遇到，感觉是和bios设置有关。

**Comment by FrazeWu** [comment]
请问catalina直接换efi，然后更新可以吗？

**Comment by zlylong** [comment]
> 请问catalina直接换efi，然后更新可以吗？

理论上是可以的

**Comment by csrutil** [comment]
基本上所有的系统都可以直接使用。

**Comment by FrazeWu** [comment]
> > 请问catalina直接换efi，然后更新可以吗？
> 
> 理论上是可以的

安装成功了

**Comment by HungYuHei** [comment]
有人试过能接双显示器吗？DP + HDMI
