### ISSUE TITLE
首次开机hdmi花屏

### ISSUE THREAD

**Issue by zlylong** [csrutil/DeskMini#7]
是只有我一个人有这样的情况吗？花屏之后，拔插HDMI线或者重启显示器就正常了。

**Comment by mz-soft** [comment]
I have your problems, too。

**Comment by mz-soft** [comment]
I tried 10.15.4 to upgrade 11.1 yesterday but failed.

Using Recovery to connect the DP display alone, the online installation of 11.1 was successful.

Then boot up and access the DP HDMI dual screen HDMI flower screen. You need to restart the HDMI display or plug in HDMI.
